# URL of system under test with ip/domain:port
url : https://api.github.com
# Below are used for REST API authentication.. Note: Structure should not be modifie.

#auth : True
## Auth type should be HTTPBasicAuth or HTTPDigestAuth
#auth_type : HTTPBasicAuth
## Need to provide user credentials as username,password
#auth_details :
#  username: elegant080449@gmail.com
#  password: mi@redmi1s
# Authentication types
Authentication_Type: HTTPBasicAuth
HTTPBasicAuth:
  username: elegant080449@gmail.com
  password: mi@redmi1s
HTTPDigestAuth:
  username: null
  password: null
Session:
  cookie_header:
    header: 'sample cookie'
  cookie_auth:
    username: 'user'
    password: 'password'
JWT:
  secret: null
  algorithm: null

# Oauth2 authorization implementation parameters
Oauth:
  client_id: null
  client_secret: null
  auth_url: null
  token_url: null

#Make rest_header when you want to send any custom headers
headers:
  "Content-Type": "application/json"
Response_wait_time: null